ads:
  host: localhost
  port: 3001
  certificate: ./certificate.pem
  key: ./key.pem

defaults:
  # cluster
  connect-timeout: 5
  load-balancer:
    least-request:
      choice-count: 2
  circuit-breaker:
    max-connections: 1024
    max-pending-requests: 1024
    max-requests: 1024
    max-retries: 3
#  outlier_detection: ???
#  http_options: ???
#  transport_socket: ??? # just 'sni'
#  metadata: ??? # cluster-only?
#  protocol_selection: ??? # h1/h2/downstream
#  tcp_keepalive: ???
  # route
#  timeout: 1s
#  retry_policy: ???

destinations:
  my-service:
    discovery: static
    hosts:
    - host: 127.0.0.1
      port: 82
    - host: 127.0.0.1
      port: 83
  google:
    discovery: strict-dns
    name: google.com

listeners:
  default:
    host: 0.0.0.0
    port: 9000
    http:
    - when:
        authority: { value: google.com }
      then:
        # conditions could be nested
      - when:
          path: { prefix: /search }
        then:
        - destination: google
    - when:
        all:
        - method: { value: GET }
        - path:
            prefix: /my-svc/
        - not:
            header:
              name: x-route-to
              prefix: 'proxy-'
      then:
        # you could omit array when using single element
        destination: my-service
