ads:
  host: localhost
  port: 3001
  certificate: ./certificate.pem
  key: ./key.pem

destinations:
  my-service:
    discovery: static
    hosts:
    - host: 127.0.0.1
      port: 82
    - host: 127.0.0.1
      port: 83
    connect-timeout: 333ms
    load-balancer:
      round-robin: {}
    circuit-breaker:
      max-connections: 128
      max-pending-requests: 64
      max-requests: 128
      max-retries: 2
    outlier-detection:
      interval: 500ms
      base-ejection-time: 30s
      max-ejection-percent: 10
      consecutive-5xx:
        num: 5
        enforcing: 100
      consecutive-gateway-failure:
        num: 5
        enforcing: 0
      success-rate:
        minimum-hosts: 5
        request-volume: 100
        stdev-factor: 1900
        enforcing: 100
      failure-percentage:
        minimum-hosts: 5
        request-volume: 50
        threshold: 85
        enforcing: 0
      local-origin:
        consecutive:
          num: 5
          enforcing: 100
        success-rate:
          enforcing: 100
        failure-percentage:
          enforcing: 100
    healthy-panic-threshold: 71
    tls: {}
    tcp-keepalive:
      probes: 3
      time: 60s
      interval: 10s
    http-options:
      idle-timeout: 123s
      http-version: downstream # h1, h2
    request-timeout: 7s
    retry-policy:
      retriable-status-codes: [ 502, 504 ]
      num-retries: 3
      per-try-timeout: 3s
      retry-back-off:
        base-interval: 32ms
        max-interval: 440ms
  google:
    discovery: strict-dns
    hosts:
      host: google.com
      port: 80
    tls:
      sni: google.com

listeners:
  default:
    host: 0.0.0.0
    port: 9000
    http:
    - when:
        all:
        - path: { prefix: /v1 }
        - openapi:
            file: /tmp/petstore.yaml
      then:
        destination: my-service
    - when:
        authority: { value: google.com }
      then:
        # conditions could be nested
      - when:
          path: { prefix: /search }
        then:
        - destination: google
    - when:
        all:
        - method: { value: GET }
        - path:
            prefix: /my-svc/
        - not:
            header:
              name: x-route-to
              prefix: 'proxy-'
      then:
        # you could omit array when using single element
        destination: my-service
